# Generated by Django 5.1.3 on 2024-11-06 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='departamentos',
            fields=[
                ('idDepto', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('numeroDepto', models.IntegerField()),
                ('torre', models.CharField(max_length=1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='deuda',
            fields=[
                ('idDeuda', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('monto', models.IntegerField()),
                ('fechaDeuda', models.DateField()),
                ('fechaVencimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='habitante',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=300)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.IntegerField()),
                ('contactoEmergencia', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Boletapago',
            fields=[
                ('idPago', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fechaPago', models.DateTimeField()),
                ('depto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Arqui.departamentos')),
                ('monto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Arqui.deuda')),
            ],
        ),
        migrations.CreateModel(
            name='deptoHabitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateField()),
                ('fechaTermino', models.DateField(null=True)),
                ('idDepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Arqui.departamentos')),
                ('rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Arqui.habitante')),
            ],
        ),
    ]
