# Generated by Django 5.0.6 on 2024-11-13 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroDepto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.BigIntegerField()),
                ('fechaDeuda', models.DateTimeField()),
                ('fechaVencimiento', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Habitante',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=300)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.IntegerField()),
                ('contactoEmergencia', models.IntegerField()),
                ('habitante_tipo', models.CharField(choices=[('A', 'Arrendatario'), ('P', 'Propietario')], default='P', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Torre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTorre', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='DeptoHabitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateTimeField()),
                ('fechaTermino', models.DateTimeField(null=True)),
                ('depto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Arqui.departamentos')),
                ('habitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Arqui.habitante')),
            ],
        ),
        migrations.CreateModel(
            name='BoletaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaPago', models.DateTimeField(null=True)),
                ('estado', models.CharField(choices=[('P', 'Pagado'), ('N', 'No Pagado'), ('A', 'Anulado'), ('R', 'Rechazado')], default='N', max_length=1)),
                ('depto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Arqui.deptohabitante')),
                ('deuda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Arqui.deuda')),
            ],
        ),
        migrations.AddField(
            model_name='departamentos',
            name='torre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Arqui.torre'),
        ),
    ]
