# Generated by Django 5.1.3 on 2024-11-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arqui', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deptohabitante',
            old_name='rut',
            new_name='habitante',
        ),
        migrations.RemoveField(
            model_name='deptohabitante',
            name='idDepto',
        ),
        migrations.AddField(
            model_name='boletapago',
            name='estado',
            field=models.CharField(choices=[('P', 'Pagado'), ('N', 'No Pagado'), ('A', 'Anulado'), ('R', 'Rechazado')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='deptohabitante',
            name='depto',
            field=models.ManyToManyField(to='Arqui.departamentos'),
        ),
        migrations.AddField(
            model_name='habitante',
            name='habitante_tipo',
            field=models.CharField(choices=[('A', 'Arrendatario'), ('P', 'Propietario')], default='P', max_length=1),
        ),
    ]
