# Generated by Django 5.1.3 on 2024-11-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arqui', '0002_rename_rut_deptohabitante_habitante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deptohabitante',
            name='fechaInicio',
            field=models.DateField(auto_now=True),
        ),
    ]
