# Generated by Django 5.1.3 on 2024-11-10 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arqui', '0004_remove_deptohabitante_depto_deptohabitante_depto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=300)),
                ('run', models.CharField(max_length=10, unique=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('fechaNacimiento', models.DateField()),
                ('fechaIngreso', models.DateField()),
                ('trabajador_tipo', models.CharField(choices=[('A', 'Administrador'), ('C', 'Conserje'), ('M', 'Mantenedor')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('idMant', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fechaInicMant', models.DateTimeField()),
                ('descripcion', models.TextField()),
                ('fechaTerminoMant', models.DateTimeField(null=True)),
                ('estado_mantenimiento', models.CharField(choices=[('P', 'Pendiente'), ('R', 'Realizado')], default='P', max_length=1)),
                ('depto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Arqui.departamentos')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimiento_trabajador', to='Arqui.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialMantenciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_inicio', to='Arqui.mantenimiento')),
                ('fechaTermino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_termino', to='Arqui.mantenimiento')),
                ('idMant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Arqui.mantenimiento')),
                ('idTrabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_trabajador', to='Arqui.trabajador')),
            ],
        ),
    ]
